export const languageMap: Record<string, string> = {
  EN: "🇬🇧 English",
  ID: "🇮🇩 Indonesian",
  ES: "🇪🇸 Spanish",
  FR: "🇫🇷 French",
  DE: "🇩🇪 German",
  ZH: "🇨🇳 Chinese",
  JA: "🇯🇵 Japanese",
  KO: "🇰🇷 Korean",
  AR: "🇸🇦 Arabic",
  HI: "🇮🇳 Hindi",
  PT: "🇵🇹 Portuguese",
  RU: "🇷🇺 Russian",
  IT: "🇮🇹 Italian",
  NL: "🇳🇱 Dutch",
  SV: "🇸🇪 Swedish",
  FI: "🇫🇮 Finnish",
  DA: "🇩🇰 Danish",
  NO: "🇳🇴 Norwegian",
  PL: "🇵🇱 Polish",
  TR: "🇹🇷 Turkish",
  TH: "🇹🇭 Thai",
  VI: "🇻🇳 Vietnamese",
  HE: "🇮🇱 Hebrew",
  EL: "🇬🇷 Greek",
  HU: "🇭🇺 Hungarian",
  CS: "🇨🇿 Czech",
  RO: "🇷🇴 Romanian",
  UK: "🇺🇦 Ukrainian",
  BG: "🇧🇬 Bulgarian",
  MS: "🇲🇾 Malay",
  FA: "🇮🇷 Persian",
  BN: "🇧🇩 Bengali",
  TL: "🇵🇭 Filipino",
  SW: "🇰🇪 Swahili",
  AF: "🇿🇦 Afrikaans",
  CA: "🇨🇦 Catalan",
  SR: "🇷🇸 Serbian",
  SK: "🇸🇰 Slovak",
  HR: "🇭🇷 Croatian",
  LT: "🇱🇹 Lithuanian",
  LV: "🇱🇻 Latvian",
  ET: "🇪🇪 Estonian",
  SL: "🇸🇮 Slovenian",
  IS: "🇮🇸 Icelandic",
};

export const languageEnum = Object.keys(languageMap).map(e=> e);